2018/09/24 20:13:06 [emerg] 8#8: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 20:18:02 [emerg] 7#7: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 20:20:11 [emerg] 7#7: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:25:39 [emerg] 8#8: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:26:10 [emerg] 8#8: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:30:27 [emerg] 8#8: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:30:53 [emerg] 8#8: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:31:21 [emerg] 8#8: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:32:14 [emerg] 8#8: getpwnam("www-api") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:33:27 [emerg] 10#10: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:34:31 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:39:09 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/24 21:40:44 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/24 22:43:33 [emerg] 7#7: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/24 22:46:24 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/24 22:47:01 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/24 22:59:22 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/24 23:00:31 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/25 21:26:13 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/25 21:27:36 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/25 21:28:06 [emerg] 8#8: unknown "web_reverse_proxy_port" variable
2018/09/25 21:46:43 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/25 22:06:17 [emerg] 8#8: getpwnam("www-app") failed in /etc/nginx/nginx.conf:1
2018/09/25 23:37:27 [emerg] 8#8: unknown "web_reverse_proxy_port" variable
2018/09/25 23:41:43 [emerg] 8#8: unknown "web_reverse_proxy_port" variable
2018/09/25 23:45:58 [error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.19.0.2:8000/", host: "localhost"
2018/09/25 23:45:58 [error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.2:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/25 23:46:05 [error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.19.0.2:8000/", host: "localhost"
2018/09/25 23:46:05 [error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.2:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/25 23:46:30 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.19.0.2:8000/", host: "localhost"
2018/09/25 23:46:30 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.2:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/26 00:05:50 [error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.3:8000/", host: "localhost"
2018/09/26 00:05:50 [error] 12#12: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/26 00:07:27 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.2:8000/", host: "localhost"
2018/09/26 00:07:28 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.2:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/26 00:07:57 [error] 11#11: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.2:8000/", host: "localhost"
2018/09/26 00:07:58 [error] 11#11: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.2:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/26 00:11:15 [error] 12#12: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.2:8000/", host: "localhost"
2018/09/26 00:11:16 [error] 12#12: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.2:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/26 00:11:16 [error] 12#12: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.2:8000/", host: "localhost"
2018/09/26 00:11:16 [error] 12#12: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.2:8000/", host: "localhost"
2018/09/26 00:11:16 [error] 12#12: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.2:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/26 00:17:09 [error] 11#11: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.2:8000/", host: "localhost"
2018/09/26 00:17:09 [error] 11#11: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.2:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2018/09/26 00:41:06 [error] 12#12: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.22.0.3:8000/", host: "localhost"
2018/09/26 00:41:09 [error] 12#12: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.22.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/"
